name: Run Once Workflow

on:
  workflow_dispatch:

jobs:
  run_once:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute script
        run: python extract_data.py
- name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update dataset $(date +'%Y-%m-%d %H:%M:%S')"
          git push
